# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Connor W. Brown"
email: "connorwbrown@berkeley.edu"
author: "Connor Brown"
description: >- # this means to ignore newlines until "baseurl:"
  Hello there! Welcome aboard.
#baseurl: "" # the subpath of your site, e.g. /blog
linkedin: "https://www.linkedin.com/in/connorwbrown/"
resume: "/assets/CBrown_Resume_v4_4.pdf"
url: "https://connorwbrown.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  "connorwbrown"

repository: "connorwbrown/connorwbrown.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
# Technical vs CompSci?
header_pages:
  - page_url: /technical/
    page_title: Technical
  - page_url: /research/
    page_title: Research
  - page_url: /data_sci/
    page_title: Data Science
  - page_url: /life/
    page_title: Life
    
proj_pages:
   - page_url: /projects/magnetic_perturbation/
     page_title: "Neural Stimulation"
     description: words words words

   - page_url: /projects/magnetic_perturbation/
     page_title: proj2
     description: proj2 desc

   - page_url: /projects/magnetic_perturbation/
     page_title: proj3
     description: proj3 desc

   - page_url: /projects/magnetic_perturbation/
     page_title: proj4
     description: proj4 desc words words words

   - page_url: /projects/magnetic_perturbation/
     page_title: proj5
     description: proj5 words words words

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - vendor
